### ISSUE TITLE
Option to select which data we want

### ISSUE THREAD

**Issue by cstayyab** [laurengarcia/url-metadata#62]
Do you plan to add the option to select which data is needed?

This can also help in reduced processing when only some data (e.g. title, description, favicon) is required.

If it is in the plan, I can help implement it and send a PR.

**Comment by laurengarcia** [comment]
I don't think it makes sense if your intention is to improve performance. Because most of the latency comes from the network call over the internet, not the post-processing this module does after it. The post-processing is probably miniscule in comparison (I've not benchmarked it tho) but typically this is the case.

If you have some special use-case where this might make sense feel free to reopen and I'll reconsider if you fill in the details about what you're looking for.

**Comment by laurengarcia** [comment]
Reopening this issue bc it is increasingly requested, and it's true that this will reduce processing for users at scale.
Sketching this out:

- Add option that accepts array `{ fields: [ 'performance', 'title', 'description', 'jsonld' ] }` 
- `fields` groups: array accepts both atomic keys and a small set of group aliases: `og`, `twitter`, `meta` etc.
- To minimize processing, a basic requirement is the extractors do not run for the rest of the set of fields returned by default, obviously.
- Include separate option `omitEmpty` which removes fields that are undefined, null, '', [], and {}, at the top-level (shallow) of metadata fields returned.

**Comment by laurengarcia** [comment]
Latest version has these changes, see "Performance Tuning" section of README in v5.9.0
https://www.npmjs.com/package/url-metadata
